# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'petromobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for petromobile

  target 'petromobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'RNFS', :path => '../node_modules/react-native-fs'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  end

  target 'petromobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'petromobile-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for petromobile-tvOS

#   target 'petromobile-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
