// LOGIN
export const START_FETCH_LOGIN = 'START_FETCH_LOGIN';
export const FETCH_ERROR_LOGIN = 'FETCH_ERROR_LOGIN';
export const FETCH_SUCCESS_LOGIN = 'FETCH_SUCCESS_LOGIN';

// CHECKIN
export const START_FETCH_CHECKIN = 'START_FETCH_CHECKIN';
export const FETCH_ERROR_CHECKIN = 'FETCH_ERROR_CHECKIN';
export const FETCH_SUCCESS_CHECKIN = 'FETCH_SUCCESS_CHECKIN';

// CHECKOUT
export const START_FETCH_CHECKOUT = 'START_FETCH_CHECKOUT';
export const FETCH_ERROR_CHECKOUT = 'FETCH_ERROR_CHECKOUT';
export const FETCH_SUCCESS_CHECKOUT = 'FETCH_SUCCESS_CHECKOUT';

// STORE TYPE
export const START_FETCH_STORE_TYPE = 'START_FETCH_STORE_TYPE';
export const FETCH_ERROR_STORE_TYPE = 'FETCH_ERROR_STORE_TYPE';
export const FETCH_SUCCESS_STORE_TYPE = 'FETCH_SUCCESS_STORE_TYPE';

// PROVINCES
export const START_FETCH_PROVINCES = 'START_FETCH_PROVINCES';
export const FETCH_ERROR_PROVINCES = 'FETCH_ERROR_PROVINCES';
export const FETCH_SUCCESS_PROVINCES = 'FETCH_SUCCESS_PROVINCES';

// DISTRICS
export const START_FETCH_DISTRICS = 'START_FETCH_DISTRICS';
export const FETCH_ERROR_DISTRICS = 'FETCH_ERROR_DISTRICS';
export const FETCH_SUCCESS_DISTRICS = 'FETCH_SUCCESS_DISTRICS';

// WARDS
export const START_FETCH_WARDS = 'START_FETCH_WARDS';
export const FETCH_ERROR_WARDS = 'FETCH_ERROR_WARDS';
export const FETCH_SUCCESS_WARDS = 'FETCH_SUCCESS_WARDS';