//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTracking.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class employeetracking_devEntities : DbContext
    {
        public employeetracking_devEntities()
            : base("name=employeetracking_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<district> district { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<employee_token> employee_token { get; set; }
        public DbSet<master_store> master_store { get; set; }
        public DbSet<province> province { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<sys_user_track_media_rm> sys_user_track_media_rm { get; set; }
        public DbSet<track> track { get; set; }
        public DbSet<track_attendance> track_attendance { get; set; }
        public DbSet<track_detail> track_detail { get; set; }
        public DbSet<track_media_rm> track_media_rm { get; set; }
        public DbSet<userclaims> userclaims { get; set; }
        public DbSet<userlogins> userlogins { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<ward> ward { get; set; }
        public DbSet<media_type> media_type { get; set; }
    }
}
