//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTracking.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class track_detail
    {
        public string Id { get; set; }
        public string FileName { get; set; }
        public string Url { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string MediaTypeId { get; set; }
        public string MediaTypeSub { get; set; }
        public string EmployeeId { get; set; }
        public bool IsActive { get; set; }
        public string CreateBy { get; set; }
        public string TrackSessionId { get; set; }
        public int PosmNumber { get; set; }
        public string OriginalFileName { get; set; }
        public Nullable<long> OriginalFileSize { get; set; }
    }
}
