//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTracking.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class track
    {
        public string Id { get; set; }
        public string EmployeeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime Date { get; set; }
        public string MaterStoreName { get; set; }
        public string HouseNumber { get; set; }
        public string StreetNames { get; set; }
        public Nullable<long> ProvinceId { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public Nullable<long> WardId { get; set; }
        public string Region { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Note { get; set; }
        public System.Guid MasterStoreId { get; set; }
        public Nullable<bool> StoreStatus { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> StoreIsChanged { get; set; }
    }
}
