//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTracking.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ward
    {
        public long Id { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public string Name { get; set; }
        public string PostalCode { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
    }
}
