//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTracking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class media_type
    {
        [Key]
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public sbyte OrderNumber { get; set; }
    }
}
