//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTracking.Data.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmplTrackingEntities : DbContext
    {
        public EmplTrackingEntities()
            : base("name=EmplTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<master_store> master_store { get; set; }
        public DbSet<sys_role> sys_role { get; set; }
        public DbSet<sys_user> sys_user { get; set; }
        public DbSet<sys_user_track_media> sys_user_track_media { get; set; }
        public DbSet<track_attendance> track_attendance { get; set; }
        public DbSet<track_media> track_media { get; set; }
    }
}
